---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://www.codeforfun.info

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'

paginator:
  layout: 'paginator'
  per_page: 10
  namespace: '/posts/'
